# Generated by Django 6.0.2 on 2026-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('qa_reply', '答疑回复'), ('system', '系统通知'), ('fsrs_reminder', '复习提醒')], db_index=True, default='system', max_length=20),
        ),
    ]
