# Generated by Django 6.0.2 on 2026-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_fsrs_reminder_to_memorix_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('qa_reply', '答疑回复'), ('system', '系统通知'), ('memorix_reminder', '复习提醒')], db_index=True, default='system', max_length=20),
        ),
    ]
