# Generated by Django 6.0.2 on 2026-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_ntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('qa_reply', '答疑回复'), ('system', '系统通知'), ('memorix_reminder', '复习提醒'), ('performance_alert', '绩效告警')], db_index=True, default='system', max_length=20),
        ),
    ]
