# Generated by Django 6.0.2 on 2026-06-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_announcement_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('qa_reply', '答疑回复'), ('system', '系统通知'), ('memorix_reminder', '复习提醒'), ('performance_alert', '绩效告警'), ('bulk_init', '初始化题库')], db_index=True, default='system', max_length=20),
        ),
    ]
