# Generated by Django 6.0.2 on 2026-08-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_ntype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncementRead',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('qa_reply', '答疑回复'), ('system', '系统通知'), ('memorix_reminder', '复习提醒'), ('performance_alert', '绩效告警'), ('bulk_init', '初始化题库'), ('join_request', '加入申请')], db_index=True, default='system', max_length=20),
        ),
    ]
