# Generated by Django 6.0.2 on 2026-04-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_contentpipelinetask'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentpipelinetask',
            new_name='quizzes_con_status_21f402_idx',
            old_name='quizzes_con_status_29fd52_idx',
        ),
        migrations.RenameIndex(
            model_name='contentpipelinetask',
            new_name='quizzes_con_task_ty_acd99f_idx',
            old_name='quizzes_con_task_ty_3366b5_idx',
        ),
    ]
