# Generated by Django 6.0.2 on 2026-04-30 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_rename_quizzes_con_status_29fd52_idx_quizzes_con_status_21f402_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userquestionstatus',
            index=models.Index(fields=['user', 'is_mastered', 'next_review_at'], name='quizzes_use_user_id_5e20b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionstatus',
            index=models.Index(fields=['user', 'wrong_count'], name='quizzes_use_user_id_0d091c_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionstatus',
            index=models.Index(fields=['user', 'last_review'], name='quizzes_use_user_id_068141_idx'),
        ),
    ]
