# Generated by Django 6.0.2 on 2026-04-30 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_userquestionstatus_quizzes_use_user_id_5e20b2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='quizzes', max_length=50, verbose_name='模板命名空间')),
                ('template_name', models.CharField(max_length=120, verbose_name='模板文件名')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('change_note', models.CharField(blank=True, max_length=200, verbose_name='变更说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['namespace', 'template_name', 'version'], name='quizzes_pro_namespa_9ec1e7_idx'), models.Index(fields=['created_at'], name='quizzes_pro_created_9c3bfa_idx')],
                'unique_together': {('namespace', 'template_name', 'version')},
            },
        ),
    ]
