# Generated by Django 6.0.2 on 2026-04-30 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_prompttemplateversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePointAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.CharField(choices=[('unknown', '未知'), ('weak', '薄弱'), ('learning', '学习中'), ('stable', '已稳定'), ('mastered', '已掌握')], default='unknown', max_length=20, verbose_name='掌握等级')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='复习优先级')),
                ('confidence_score', models.PositiveSmallIntegerField(default=0, verbose_name='信心分(0-100)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='个性标签')),
                ('note', models.TextField(blank=True, verbose_name='个性备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_annotations', to='quizzes.knowledgepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mastery_level'], name='quizzes_kno_user_id_017300_idx'), models.Index(fields=['user', 'priority'], name='quizzes_kno_user_id_54d7d2_idx'), models.Index(fields=['knowledge_point', 'updated_at'], name='quizzes_kno_knowled_af49ec_idx')],
                'unique_together': {('user', 'knowledge_point')},
            },
        ),
    ]
