# Generated by Django 6.0.2 on 2026-05-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_knowledgepointannotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSRSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.JSONField(default=list)),
                ('last_optimized_at', models.DateTimeField(blank=True, null=True)),
                ('total_reviews_used', models.IntegerField(default=0)),
                ('current_loss', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('elapsed_days', models.FloatField(help_text='距离上次复习过去的天数')),
                ('predicted_retrievability', models.FloatField()),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.knowledgepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserKnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.FloatField(default=0.0, help_text='综合掌握度评分')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.knowledgepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'knowledge_point')},
            },
        ),
    ]
