# Generated by Django 6.0.2 on 2026-05-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_fsrsprofile_reviewlog_userknowledgestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionresult',
            name='details',
            field=models.JSONField(blank=True, help_text='主观题采分明细', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rubric',
            field=models.JSONField(blank=True, help_text='主观题采分点 JSON 结构', null=True),
        ),
    ]
