# Generated by Django 6.0.2 on 2026-05-04 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_examquestionresult_details_question_rubric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSRSOptimizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_loss', models.FloatField(blank=True, null=True)),
                ('new_loss', models.FloatField(blank=True, null=True)),
                ('improvement_ratio', models.FloatField(default=0.0, help_text='(old - new) / old')),
                ('reviews_used', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_optimization_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedMockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', '可下载'), ('failed', '生成失败')], default='ready', max_length=20)),
                ('exam_pdf', models.CharField(blank=True, help_text='试卷版绝对路径', max_length=500)),
                ('answer_pdf', models.CharField(blank=True, help_text='解析版绝对路径', max_length=500)),
                ('question_count', models.IntegerField(default=0)),
                ('weak_coverage', models.IntegerField(default=0, help_text='命中的薄弱点题目数')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
