# Generated by Django 6.0.2 on 2026-05-07 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_teacherexam_studentexamsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepointannotation',
            name='source',
            field=models.CharField(choices=[('auto', '系统计算'), ('manual', '用户标注')], default='manual', max_length=10, verbose_name='数据来源'),
        ),
        migrations.AddIndex(
            model_name='knowledgepointannotation',
            index=models.Index(fields=['source'], name='quizzes_kno_source_a94089_idx'),
        ),
    ]
