# Generated by Django 6.0.2 on 2026-05-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_knowledgepointannotation_source_and_more'),
        ('users', '0020_layer2_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='users.institution', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='personalizedmockexam',
            name='status',
            field=models.CharField(choices=[('processing', '生成中'), ('ready', '可下载'), ('failed', '生成失败')], default='ready', max_length=20),
        ),
    ]
