# Generated by Django 6.0.2 on 2026-05-15 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_institution_fk'),
        ('users', '0026_membership_tier_4level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentpipelinetask',
            name='quizzes_con_status_21f402_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentpipelinetask',
            name='quizzes_con_task_ty_acd99f_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepointannotation',
            name='quizzes_kno_user_id_017300_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepointannotation',
            name='quizzes_kno_user_id_54d7d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepointannotation',
            name='quizzes_kno_knowled_af49ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgepointannotation',
            name='quizzes_kno_source_a94089_idx',
        ),
        migrations.RemoveIndex(
            model_name='prompttemplateversion',
            name='quizzes_pro_namespa_9ec1e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='prompttemplateversion',
            name='quizzes_pro_created_9c3bfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='userquestionstatus',
            name='quizzes_use_user_id_5e20b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='userquestionstatus',
            name='quizzes_use_user_id_0d091c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userquestionstatus',
            name='quizzes_use_user_id_068141_idx',
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_exams', to='users.institution', verbose_name='所属机构'),
        ),
    ]
