# Generated by Django 6.0.2 on 2026-05-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_teacherexam_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsubmission',
            name='graded_pdf',
            field=models.FileField(blank=True, help_text='教师批改后带笔迹的PDF', upload_to='graded_answers/'),
        ),
    ]
