# Generated by Django 6.0.2 on 2026-05-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0027_knowledgepoint_institution'),
        ('users', '0030_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpipelinetask',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_tasks', to='users.institution', verbose_name='所属机构'),
        ),
    ]
