# Generated by Django 6.0.2 on 2026-05-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_contentpipelinetask_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgepoint',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='同级节点中的显示顺序，数字越小越靠前', verbose_name='排序'),
        ),
    ]
