# Generated by Django 6.0.2 on 2026-05-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_alter_knowledgepoint_options_knowledgepoint_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quizzes.knowledgepoint', verbose_name='上级知识点'),
        ),
    ]
