# Generated by Django 6.0.2 on 2026-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0030_alter_knowledgepoint_parent_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='subject',
            field=models.CharField(blank=True, help_text='如 金融431、法学、IELTS 等', max_length=100, null=True, verbose_name='学科名称'),
        ),
    ]
