# Generated by Django 6.0.2 on 2026-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0031_knowledgepoint_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepoint',
            name='subject',
            field=models.CharField(blank=True, help_text='如 金融431、法学、CPA 等', max_length=100, null=True, verbose_name='学科名称'),
        ),
    ]
