# Generated by Django 6.0.2 on 2026-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0032_alter_knowledgepoint_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpipelinetask',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('running', '执行中'), ('review', '待审核'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('entry', '入门 (Entry)'), ('easy', '简单 (Easy)'), ('normal', '适当 (Normal)'), ('hard', '困难 (Hard)'), ('extreme', '极限 (Extreme)')], db_index=True, default='normal', max_length=20, verbose_name='难度等级'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('objective', '客观题'), ('subjective', '主观题')], db_index=True, default='objective', max_length=20),
        ),
        migrations.AlterField(
            model_name='userquestionstatus',
            name='next_review_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
