# Generated by Django 6.0.2 on 2026-05-25 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0034_rename_fsrs_to_memorix'),
        ('users', '0042_examtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='适用学科')),
                ('difficulty', models.CharField(choices=[('entry', '入门'), ('easy', '简单'), ('normal', '适当'), ('hard', '困难'), ('extreme', '极限'), ('mixed', '混合')], default='normal', max_length=20)),
                ('question_types', models.JSONField(default=list, help_text='["objective","subjective"]')),
                ('type_ratio', models.JSONField(default=dict, help_text='{"objective": 0.7, "short": 0.2, "essay": 0.1}')),
                ('question_count', models.IntegerField(default=10)),
                ('knowledge_point_ids', models.JSONField(blank=True, default=list, help_text='预选知识点ID列表')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统预设')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.institution')),
            ],
            options={
                'ordering': ['-is_system', '-updated_at'],
            },
        ),
    ]
