# Generated by Django 6.0.2 on 2026-06-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0036_seed_system_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionstatus',
            name='error_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userquestionstatus',
            name='error_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
