# Generated by Django 6.0.2 on 2026-06-06 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0037_add_error_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('is_correct', models.BooleanField()),
                ('error_type', models.CharField(blank=True, default='', max_length=32)),
                ('error_metadata', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
