# Generated by Django 6.0.2 on 2026-06-06 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0038_add_grading_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemParameter',
            fields=[
                ('question', models.OneToOneField(help_text='关联的题目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quizzes.question')),
                ('discrimination', models.FloatField(default=1.0, help_text='IRT a参数，区分度')),
                ('difficulty', models.FloatField(default=0.0, help_text='IRT b参数，难度')),
                ('guessing', models.FloatField(default=0.25, help_text='IRT c参数，猜测概率')),
                ('responses_count', models.IntegerField(default=0, help_text='用于估计的答题次数')),
                ('last_estimated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QMatrixEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, help_text='该题是否需要掌握此知识点才能答对')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.knowledgepoint')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
            ],
            options={
                'unique_together': {('question', 'knowledge_point')},
            },
        ),
        migrations.CreateModel(
            name='UserAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theta', models.FloatField(default=0.0, help_text='IRT θ参数，学生能力')),
                ('responses_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.knowledgepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'knowledge_point')},
            },
        ),
    ]
