# Generated by Django 6.0.2 on 2026-06-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0039_add_irt_models'),
        ('users', '0048_user_agreed_to_terms_user_agreed_to_terms_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_type', models.CharField(choices=[('contains', '包含'), ('prerequisite', '前驱'), ('similar', '相似'), ('contrast', '对立'), ('confusion', '混淆'), ('co_occur', '共现'), ('derivation', '推导')], max_length=16)),
                ('weight', models.FloatField(default=1.0, help_text='扩散权重 [0, 1]')),
                ('source_type', models.CharField(choices=[('tree', '从 KnowledgePoint 树派生'), ('llm', 'LLM 批量生成'), ('manual', '手工标注'), ('data', 'ReviewLog 数据驱动')], default='tree', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='权重<0.05自动标记为False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, help_text='机构专属边（NULL=全局）', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.institution')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='quizzes.knowledgepoint')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='quizzes.knowledgepoint')),
            ],
            options={
                'verbose_name': '知识图边',
                'verbose_name_plural': '知识图边',
                'indexes': [models.Index(fields=['source', 'is_active'], name='quizzes_kno_source__ce10d1_idx'), models.Index(fields=['target', 'is_active'], name='quizzes_kno_target__76c749_idx'), models.Index(fields=['institution', 'is_active'], name='quizzes_kno_institu_3c5fc5_idx'), models.Index(fields=['source_type'], name='quizzes_kno_source__f54362_idx')],
                'unique_together': {('source', 'target', 'edge_type', 'institution')},
            },
        ),
    ]
