# Generated by Django 6.0.2 on 2026-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0042_add_institution_to_irt_models'),
        ('users', '0051_class'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemparameter',
            name='unique_question_institution',
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='itemparameter',
            unique_together={('question', 'institution')},
        ),
    ]
