# Generated by Django 6.0.2 on 2026-06-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0044_assignment_models_existing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexam',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='考试时长(分钟)'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='exam_type',
            field=models.CharField(choices=[('pdf', 'PDF试卷'), ('online', '在线考试')], default='pdf', max_length=10, verbose_name='考试类型'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='最大尝试次数'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='passing_score',
            field=models.FloatField(blank=True, null=True, verbose_name='及格分数'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='选项乱序'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='shuffle_questions',
            field=models.BooleanField(default=True, verbose_name='题目乱序'),
        ),
        migrations.AddField(
            model_name='teacherexam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开考时间'),
        ),
        migrations.AlterField(
            model_name='teacherexam',
            name='exam_pdf',
            field=models.FileField(blank=True, help_text='PDF 模式试卷文件，online 模式可空', null=True, upload_to='teacher_exams/'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.FloatField(default=1.0, verbose_name='本题分值')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='quizzes.teacherexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='OnlineExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', '作答中'), ('submitted', '已提交'), ('graded', '已批改')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(default=dict, help_text='{question_id: user_answer}')),
                ('question_order', models.JSONField(default=list, help_text='该学生看到的题目顺序 [question_id, ...]')),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('question_results', models.JSONField(blank=True, default=list, help_text='[{question_id, score, max_score, is_correct, feedback}]')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.teacherexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
