# Generated by Django 6.0.2 on 2026-06-20 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0047_add_assignment_submission_question_results'),
        ('users', '0059_add_institution_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='健康分 (0-100)')),
                ('level', models.CharField(choices=[('healthy', '健康'), ('at_risk', '注意'), ('critical', '危险')], max_length=20, verbose_name='健康等级')),
                ('components', models.JSONField(default=dict, verbose_name='分维度得分')),
                ('details', models.JSONField(default=dict, verbose_name='诊断详情')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='快照日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_health_snapshots', to='users.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康快照',
                'verbose_name_plural': '健康快照',
                'ordering': ['-snapshot_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'snapshot_date'), name='unique_health_snapshot_per_day')],
            },
        ),
    ]
