# Generated by Django 6.0.2 on 2026-06-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0048_add_student_health_snapshot'),
        ('users', '0061_add_api_sso_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='商品标题')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('content_type', models.CharField(choices=[('question_set', '题库'), ('course', '课程'), ('exam_template', '出题模板')], max_length=20, verbose_name='内容类型')),
                ('content_ids', models.JSONField(default=list, help_text='{question_ids: [], course_ids: []}', verbose_name='内容 ID 列表')),
                ('subject', models.CharField(max_length=100, verbose_name='学科')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='适用年级')),
                ('price_cents', models.IntegerField(default=0, verbose_name='价格(分)')),
                ('license_type', models.CharField(choices=[('free', '免费'), ('one_time', '买断'), ('subscription', '订阅')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已上架'), ('unpublished', '已下架')], db_index=True, default='draft', max_length=20)),
                ('downloads', models.IntegerField(default=0, verbose_name='下载/购买次数')),
                ('rating', models.FloatField(default=0, verbose_name='平均评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_listings', to='users.institution')),
            ],
            options={
                'verbose_name': '市场列表',
                'verbose_name_plural': '市场列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
