# Generated by Django 6.0.2 on 2026-06-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0049_add_api_sso_marketplace'),
        ('users', '0061_add_api_sso_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_listings', to='users.institution'),
        ),
    ]
