# Generated by Django 6.0.2 on 2026-06-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0050_marketplace_publisher_nullable'),
        ('users', '0065_populate_personal_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorixFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decay', models.FloatField(default=0.02, help_text='α: 自然衰减率/天')),
                ('beta_e', models.FloatField(default=0.005, help_text='βe: 扩散强度')),
                ('beta_a', models.FloatField(default=0.5, help_text='βa: 评分放大系数')),
                ('eta', models.FloatField(default=0.02, help_text='η: 复习转移系数')),
                ('brier_score', models.FloatField(blank=True, help_text='最近 7 天 Brier score', null=True)),
                ('reviews_evaluated', models.IntegerField(default=0, help_text='评估窗口内的复习次数')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('perturbation_param', models.CharField(blank=True, help_text='正在测试的参数名: decay/beta_e/beta_a/eta', max_length=16, null=True)),
                ('perturbation_multiplier', models.FloatField(blank=True, help_text='扰动倍率: 1.1 或 0.9', null=True)),
                ('perturbation_brier_before', models.FloatField(blank=True, help_text='扰动前的 Brier score', null=True)),
                ('perturbation_original_value', models.FloatField(blank=True, help_text='扰动前的参数值', null=True)),
                ('last_perturbed_at', models.DateTimeField(blank=True, null=True)),
                ('perturbation_history', models.JSONField(blank=True, default=list, help_text='[{param, old, new, brier_before, brier_after, accepted, at}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(blank=True, help_text='NULL=全局默认，不参与自进化', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorix_field_config', to='users.institution')),
            ],
            options={
                'verbose_name': 'Memorix Field 机构配置',
                'verbose_name_plural': 'Memorix Field 机构配置',
            },
        ),
    ]
