# Generated by Django 6.0.2 on 2026-06-24 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0051_memorixfieldconfig'),
        ('users', '0065_populate_personal_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepoint',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='唯一编码(如MB-1001)'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='level',
            field=models.CharField(choices=[('sub', '模块(SUB)'), ('ch', '篇章(CH)'), ('sec', '小节(SEC)'), ('kp', '考点(KP)')], db_index=True, default='kp', max_length=10, verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='subject',
            field=models.CharField(blank=True, db_index=True, help_text='如 金融431、法学、CPA 等', max_length=100, null=True, verbose_name='学科名称'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['edge_type', 'is_active'], name='quizzes_kno_edge_ty_c169fe_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestionstatus',
            index=models.Index(fields=['user', 'next_review_at'], name='quizzes_use_user_id_10ffbc_idx'),
        ),
    ]
