# Generated by Django 6.0.2 on 2026-08-14 05:27

from django.db import migrations


def drop_legacy_tables(apps, schema_editor):
    """清理历史遗留表（早期 AssignmentQuestionResult 独立表，M2M through 表由 DeleteModel 自动删除）。"""
    schema_editor.execute('DROP TABLE IF EXISTS quizzes_assignmentquestionresult')


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0052_alter_knowledgepoint_code_alter_knowledgepoint_level_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_legacy_tables, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AssignmentQuestion',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
        migrations.DeleteModel(
            name='OnlineExamAttempt',
        ),
        migrations.DeleteModel(
            name='StudentExamSubmission',
        ),
        migrations.DeleteModel(
            name='TeacherExam',
        ),
        migrations.DeleteModel(
            name='PersonalizedMockExam',
        ),
        migrations.DeleteModel(
            name='ExamTemplate',
        ),
    ]
