# Generated by Django 6.0.2 on 2026-05-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_bot_is_exclusive'),
        ('users', '0040_remove_institutionrewardconfig_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='users.institution', verbose_name='所属机构'),
        ),
        migrations.CreateModel(
            name='BotVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否对学员可见')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for', to='ai_assistant.bot')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_bots', to='users.institution')),
            ],
            options={
                'verbose_name': '机器人可见性',
                'verbose_name_plural': '机器人可见性',
                'unique_together': {('institution', 'bot')},
            },
        ),
    ]
