# Generated by Django 6.0.2 on 2026-05-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_bot_institution_botvisibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('assistant', '助教'), ('planner', '学习规划师')], default='assistant', max_length=20, verbose_name='机器人类型'),
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('summary', models.TextField(blank=True, verbose_name='AI 生成的计划摘要')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('archived', '已归档')], db_index=True, default='active', max_length=20)),
                ('plan_data', models.JSONField(default=dict, help_text='AI 生成的完整计划 JSON，包含 tasks 数组')),
                ('auto_generated', models.BooleanField(default=False, help_text='是否由 AI 自动生成')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='ai_assistant.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
