# Generated by Django 6.0.2 on 2026-05-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_bot_bot_type_studyplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('preference', '偏好'), ('academic', '学业'), ('interaction', '交互'), ('teacher_context', '教师上下文')], db_index=True, default='preference', max_length=20)),
                ('key', models.CharField(help_text='如: 偏好数学推导风格', max_length=200, verbose_name='记忆键')),
                ('value', models.TextField(help_text='如: 喜欢用具体例子先引入，再给出严格证明', verbose_name='记忆值')),
                ('source', models.CharField(choices=[('auto', 'AI提取'), ('manual', '用户设置')], default='auto', max_length=20)),
                ('confidence', models.FloatField(default=0.5, help_text='置信度 0-1')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'memory_type', 'is_active'], name='ai_assistan_user_id_9f7bd4_idx')],
            },
        ),
    ]
