# Generated by Django 6.0.2 on 2026-05-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_agentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='工具返回的结构化数据（如生成的题目、管线 task_id）'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('assistant', '助教'), ('planner', '学习规划师'), ('exam_generator', '出题助手')], default='assistant', max_length=20, verbose_name='机器人类型'),
        ),
    ]
