# Generated by Django 6.0.2 on 2026-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_exam_generator_bot_and_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='institution_personality',
            field=models.JSONField(blank=True, default=dict, help_text='机构自定义人格配置：教学风格、知识范围、语气等', verbose_name='机构人格配置'),
        ),
    ]
