# Generated by Django 6.0.2 on 2026-05-29 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_add_institution_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='会话 ID，用于区分不同对话'),
        ),
    ]
