# Generated by Django 6.0.2 on 2026-05-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_alter_bot_bot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('planner', '学习教练'), ('exam_generator', '命题官')], default='planner', max_length=20, verbose_name='机器人类型'),
        ),
    ]
