# Generated by Django 6.0.2 on 2026-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_alter_bot_bot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatmessage',
            name='conversation_id',
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('assistant', '助教'), ('planner', '学习规划师'), ('exam_generator', '出题助手')], default='assistant', max_length=20, verbose_name='机器人类型'),
        ),
    ]
