# Generated by Django 6.0.2 on 2026-05-31 12:17

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0012_add_memory_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='会话 ID，用于区分不同对话'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('planner', '学习教练'), ('exam_generator', '命题官')], default='planner', max_length=20, verbose_name='机器人类型'),
        ),
        migrations.AddIndex(
            model_name='agentmemory',
            index=models.Index(fields=['user', 'is_active', 'confidence'], name='ai_assistan_user_id_a15734_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentmemory',
            constraint=models.UniqueConstraint(fields=('user', 'memory_type', 'key'), name='uniq_user_memory_type_key'),
        ),
    ]
