# Generated by Django 6.0.2 on 2026-06-01 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0013_aichatmessage_conversation_id_alter_bot_bot_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCardInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200, verbose_name='卡片标题')),
                ('card_action_type', models.CharField(choices=[('video', '视频'), ('quiz', '做题'), ('review', '复习'), ('course', '课程'), ('chart', '图表'), ('plan', '计划'), ('exam', '考试')], max_length=20, verbose_name='动作类型')),
                ('card_action_url', models.CharField(max_length=500, verbose_name='跳转 URL')),
                ('card_icon', models.CharField(blank=True, default='', max_length=20, verbose_name='图标类型')),
                ('card_description', models.TextField(blank=True, default='', verbose_name='卡片描述')),
                ('clicked', models.BooleanField(default=True, verbose_name='已点击')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外数据：题目 ID、课程 ID 等')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '行动卡片交互',
                'verbose_name_plural': '行动卡片交互',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['user', 'card_action_type'], name='ai_assistan_user_id_0e87cc_idx'), models.Index(fields=['user', 'completed'], name='ai_assistan_user_id_b884f5_idx')],
            },
        ),
    ]
