# Generated by Django 6.0.2 on 2026-06-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_add_action_card_interaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('messages', models.JSONField(help_text='完整对话记录')),
                ('tool_calls', models.JSONField(default=list, help_text='工具调用序列')),
                ('tool_outputs', models.JSONField(default=list, help_text='工具返回结果')),
                ('outcome', models.CharField(choices=[('success', '成功'), ('partial', '部分成功'), ('failure', '失败'), ('unknown', '未知')], default='unknown', max_length=20)),
                ('outcome_metrics', models.JSONField(default=dict, help_text='结果指标：掌握率变化、任务完成度等')),
                ('prompt_variant', models.CharField(default='baseline', help_text='使用的 prompt 变体标识', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='结果评估时间', null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='ai_assistant.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '对话轨迹',
                'verbose_name_plural': '对话轨迹',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'bot', 'created_at'], name='ai_assistan_user_id_9ae937_idx'), models.Index(fields=['conversation_id'], name='ai_assistan_convers_0b2191_idx'), models.Index(fields=['outcome', 'created_at'], name='ai_assistan_outcome_86d362_idx')],
            },
        ),
    ]
