# Generated by Django 6.0.2 on 2026-06-06 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0015_aitrajectory'),
        ('users', '0048_user_agreed_to_terms_user_agreed_to_terms_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('learning_style', models.CharField(blank=True, choices=[('formula_oriented', '公式导向'), ('visual_learner', '视觉型'), ('example_driven', '示例驱动'), ('memorization_oriented', '记忆导向'), ('balanced', '均衡')], default='balanced', max_length=32)),
                ('response_length', models.CharField(blank=True, choices=[('prefers_brief', '偏好简洁'), ('prefers_detailed', '偏好详细'), ('balanced', '均衡')], default='balanced', max_length=32)),
                ('interaction_style', models.CharField(blank=True, choices=[('deep_questioner', '深度提问者'), ('critical_thinker', '批判性思维者'), ('passive_learner', '被动学习者')], default='passive_learner', max_length=32)),
                ('cognitive_state', models.CharField(blank=True, choices=[('focused', '专注'), ('anxious', '焦虑'), ('overwhelmed', '不堪重负'), ('motivated', '积极进取')], default='focused', max_length=32)),
                ('domain_expertise', models.CharField(blank=True, choices=[('beginner', '初学者'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_analysis', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户画像',
                'verbose_name_plural': '用户画像',
            },
        ),
    ]
