# Generated by Django 6.0.2 on 2026-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0017_add_conversation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='feedback',
            field=models.BooleanField(blank=True, default=None, help_text='用户反馈：True=赞，False=踩，null=未评价', null=True),
        ),
    ]
