# Generated by Django 6.0.2 on 2026-06-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0018_add_feedback_to_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('prompt', 'Prompt 策略'), ('memory', '个体记忆'), ('tool', '工具配置'), ('workflow', '工作流模式')], max_length=20)),
                ('scope_type', models.CharField(choices=[('global', '全局生效'), ('student', '指定学生'), ('kp_chain', '知识依赖链'), ('institution', '指定机构')], default='global', max_length=20)),
                ('scope_value', models.JSONField(default=dict, help_text='作用范围实体，如 {"student_id": 123, "kp_id": 45}')),
                ('title', models.CharField(help_text='规律一句话摘要', max_length=200)),
                ('trigger', models.JSONField(default=dict, help_text='触发条件表达式')),
                ('effect', models.JSONField(default=dict, help_text='规律内容与参数')),
                ('confidence', models.CharField(choices=[('low', '建议（临时注入，不持久化）'), ('medium', '验证中（小流量 A/B）'), ('high', '持久化（已通过反事实验证）')], default='low', max_length=10)),
                ('weight', models.FloatField(default=1.0, help_text='权重 = 验证次数 × 最近 Δmastery')),
                ('status', models.CharField(choices=[('active', '活跃'), ('dormant', '休眠（60天未触发）'), ('archived', '归档（90天未触发）'), ('retired', '淘汰（验证失败）')], default='active', max_length=20)),
                ('verify_count', models.PositiveIntegerField(default=0, help_text='验证通过次数')),
                ('verify_fail_count', models.PositiveIntegerField(default=0, help_text='验证失败次数')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trajectory', models.ForeignKey(blank=True, help_text='来源轨迹', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='ai_assistant.aitrajectory')),
                ('user', models.ForeignKey(blank=True, help_text='规律发现者（全局规律可为 null）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '经验规律',
                'verbose_name_plural': '经验规律',
                'ordering': ['-weight', '-created_at'],
                'indexes': [models.Index(fields=['dimension', 'status', 'confidence'], name='ai_assistan_dimensi_640273_idx'), models.Index(fields=['scope_type', 'scope_value'], name='ai_assistan_scope_t_7c1b89_idx'), models.Index(fields=['status', 'last_triggered_at'], name='ai_assistan_status_e40df6_idx')],
            },
        ),
    ]
