# Generated by Django 6.0.2 on 2026-06-14 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0019_add_experience_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_id', models.PositiveIntegerField(help_text='触发验证的知识点 ID')),
                ('score', models.FloatField(help_text='得分')),
                ('max_score', models.FloatField(help_text='满分')),
                ('score_ratio', models.FloatField(help_text='得分率 score/max_score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='ai_assistant.experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '经验验证记录',
                'verbose_name_plural': '经验验证记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['experience', 'user'], name='ai_assistan_experie_5c7e01_idx'), models.Index(fields=['experience', 'created_at'], name='ai_assistan_experie_68bb2f_idx')],
            },
        ),
    ]
