# Generated by Django 6.0.2 on 2026-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0020_add_experience_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncardinteraction',
            name='card_action_type',
            field=models.CharField(choices=[('video', '视频'), ('quiz', '做题'), ('review', '复习'), ('course', '课程'), ('chart', '图表'), ('plan', '计划'), ('exam', '考试'), ('reply', '回复')], max_length=20, verbose_name='动作类型'),
        ),
    ]
