# Generated by Django 6.0.2 on 2026-06-21 15:10
# Re-purposed: 目标字段移到 TeachingPlan，StudyPlan 只加 teaching_plan FK

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0021_add_reply_action_type'),
        ('courses', '0019_add_teaching_plan_models'),  # TeachingPlan created here
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='teaching_plan',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='student_plans', to='courses.TeachingPlan',
                verbose_name='关联教学计划'
            ),
        ),
    ]
