# Generated by Django 6.0.2 on 2026-06-25 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0022_add_study_plan_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['user', 'bot', 'timestamp'], name='ai_chat_user_bot_ts_idx'),
        ),
    ]
