# Generated by Django 6.0.2 on 2026-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0023_add_chat_message_user_bot_ts_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('planner', '学习教练'), ('exam_generator', '工作台')], default='planner', max_length=20, verbose_name='机器人类型'),
        ),
    ]
