# Generated by Django 6.0.2 on 2026-08-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0024_alter_bot_bot_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
