# Generated by Django 6.0.2 on 2026-05-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_system', '0002_answer_updated_at'),
        ('faq_system', '0002_question_followers'),
    ]

    operations = [
    ]
