# Generated by Django 6.0.2 on 2026-05-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_system', '0003_merge_0002_answer_updated_at_0002_question_followers'),
        ('users', '0026_membership_tier_4level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_questions', to='users.institution', verbose_name='所属机构'),
        ),
    ]
