"""
Django settings for school_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

def _get_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _get_list(name: str, default=None):
    raw = os.getenv(name, "")
    values = [item.strip() for item in raw.split(",") if item.strip()]
    return values if values else (default or [])


def _get_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None or str(value).strip() == "":
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc


DJANGO_ENV = os.getenv("DJANGO_ENV", "development").strip().lower()
IS_PROD = DJANGO_ENV in {"production", "prod"}

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-default")
DEBUG = _get_bool("DEBUG", default=not IS_PROD)

if IS_PROD and SECRET_KEY == "django-insecure-default":
    raise ImproperlyConfigured("SECRET_KEY must be set in production.")
if IS_PROD and DEBUG:
    raise ImproperlyConfigured("DEBUG must be False in production.")

ALLOWED_HOSTS = _get_list(
    "ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost", "0.0.0.0"] if DEBUG else [],
)
if IS_PROD and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be configured in production.")

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "corsheaders",
    "channels",
    "users",
    "courses",
    "articles",
    "quizzes",
    "study_room",
    "ai_assistant",
    "faq_system",
    "notifications",
    "interviews",
    "core",
    "payments",
]

MIDDLEWARE = [
    "school_system.middleware.RequestIDMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "school_system.middleware.SecurityHeadersMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "school_system.middleware.APIAccessLogMiddleware",
    "school_system.middleware.APIExceptionMiddleware",
]

ROOT_URLCONF = "school_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "school_system.wsgi.application"
ASGI_APPLICATION = "school_system.asgi.application"

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", ""),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("CACHE_REDIS_URL", "redis://127.0.0.1:6379/1"),
        "KEY_PREFIX": "unimind",
        "TIMEOUT": 300,
    }
}

AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    # Add other static files here if any
]
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CORS_ALLOW_ALL_ORIGINS = _get_bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)
if IS_PROD and CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured("CORS_ALLOW_ALL_ORIGINS must be False in production.")
CORS_ALLOWED_ORIGINS = _get_list("CORS_ALLOWED_ORIGINS")
CORS_ALLOWED_ORIGIN_REGEXES = _get_list("CORS_ALLOWED_ORIGIN_REGEXES")
CORS_ALLOW_CREDENTIALS = _get_bool("CORS_ALLOW_CREDENTIALS", default=True)
CSRF_TRUSTED_ORIGINS = _get_list("CSRF_TRUSTED_ORIGINS")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")

SESSION_COOKIE_SECURE = _get_bool("SESSION_COOKIE_SECURE", default=IS_PROD)
CSRF_COOKIE_SECURE = _get_bool("CSRF_COOKIE_SECURE", default=IS_PROD)
SECURE_SSL_REDIRECT = _get_bool("SECURE_SSL_REDIRECT", default=IS_PROD)
SECURE_HSTS_SECONDS = _get_int("SECURE_HSTS_SECONDS", 31536000 if IS_PROD else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _get_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=IS_PROD)
SECURE_HSTS_PRELOAD = _get_bool("SECURE_HSTS_PRELOAD", default=IS_PROD)
SECURE_REFERRER_POLICY = os.getenv(
    "SECURE_REFERRER_POLICY",
    "strict-origin-when-cross-origin" if IS_PROD else "same-origin",
)
SECURE_CONTENT_TYPE_NOSNIFF = _get_bool("SECURE_CONTENT_TYPE_NOSNIFF", default=IS_PROD)
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY" if IS_PROD else "SAMEORIGIN")

if _get_bool("USE_X_FORWARDED_PROTO", default=IS_PROD):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.CookieTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "2000/hour",
        "anon": "120/hour",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# DRF Spectacular (OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    "TITLE": "UniMind.ai API",
    "DESCRIPTION": "Agent 驱动的智能教育基础设施 API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {"name": "auth", "description": "认证与用户管理"},
        {"name": "ai", "description": "AI Agent 对话"},
        {"name": "quizzes", "description": "题库与考试"},
        {"name": "courses", "description": "课程管理"},
        {"name": "institution", "description": "机构管理"},
    ],
}

ONLINE_USER_ACTIVE_WINDOW_SECONDS = _get_int("ONLINE_USER_ACTIVE_WINDOW_SECONDS", 300)
LLM_REQUEST_TIMEOUT_SECONDS = _get_int("LLM_REQUEST_TIMEOUT_SECONDS", 120)
LLM_REQUEST_MAX_RETRIES = _get_int("LLM_REQUEST_MAX_RETRIES", 1)
AI_SCHEMA_REPAIR_MAX_RETRIES = _get_int("AI_SCHEMA_REPAIR_MAX_RETRIES", 1)
AI_BULK_GENERATE_MAX_PER_REQUEST = _get_int("AI_BULK_GENERATE_MAX_PER_REQUEST", 3)
AI_BULK_GENERATE_CONCURRENCY = _get_int("AI_BULK_GENERATE_CONCURRENCY", 4)
AI_DIFFICULTY_CHECK_ENABLED = _get_bool("AI_DIFFICULTY_CHECK_ENABLED", default=True)
QUIZ_EXAM_GRADING_USE_CELERY = _get_bool("QUIZ_EXAM_GRADING_USE_CELERY", default=True)

# ELO 积分系统
ELO_K_FACTOR = _get_int("ELO_K_FACTOR", 32)
ELO_INITIAL_BONUS = _get_int("ELO_INITIAL_BONUS", 200)
LEADERBOARD_SIZE = _get_int("LEADERBOARD_SIZE", 50)

# 上传限制 — 匹配 nginx client_max_body_size (200MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = _get_int("DATA_UPLOAD_MAX_MEMORY_SIZE", 209715200)
FILE_UPLOAD_MAX_MEMORY_SIZE = _get_int("FILE_UPLOAD_MAX_MEMORY_SIZE", 209715200)

# ASR 语音转文字
ASR_DEFAULT_PROVIDER = os.getenv("ASR_DEFAULT_PROVIDER", "dummy")
ASR_PROVIDER_CONFIG = {
    "glm_asr": {
        "api_key": os.getenv("GLM_ASR_API_KEY", ""),
    },
    "mimo_asr": {
        "api_key": os.getenv("MIMO_ASR_API_KEY", ""),
        "base_url": os.getenv("MIMO_ASR_BASE_URL", "https://api.xiaomimimo.com/v1"),
        "model": os.getenv("MIMO_ASR_MODEL", "mimo-v2.5-asr"),
        "language": os.getenv("MIMO_ASR_LANGUAGE", "zh"),
        "timeout": int(os.getenv("MIMO_ASR_TIMEOUT", "120")),
    },
}

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
CHANNEL_LAYER_REDIS_URL = os.getenv("CHANNEL_LAYER_REDIS_URL", REDIS_URL)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_LAYER_REDIS_URL],
        },
    },
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ
CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_TASK_DEFAULT_QUEUE", "default")
CELERY_TASK_TRACK_STARTED = _get_bool("CELERY_TASK_TRACK_STARTED", default=True)
CELERY_TASK_ACKS_LATE = _get_bool("CELERY_TASK_ACKS_LATE", default=True)
CELERY_TASK_REJECT_ON_WORKER_LOST = _get_bool("CELERY_TASK_REJECT_ON_WORKER_LOST", default=True)
CELERY_WORKER_PREFETCH_MULTIPLIER = _get_int("CELERY_WORKER_PREFETCH_MULTIPLIER", 1)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = _get_bool(
    "CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP",
    default=True,
)
CELERY_BROKER_CONNECTION_MAX_RETRIES = _get_int("CELERY_BROKER_CONNECTION_MAX_RETRIES", 100)
CELERY_TASK_SOFT_TIME_LIMIT = _get_int("CELERY_TASK_SOFT_TIME_LIMIT", 1500)
CELERY_TASK_TIME_LIMIT = _get_int("CELERY_TASK_TIME_LIMIT", 1800)
CELERY_RESULT_EXPIRES = _get_int("CELERY_RESULT_EXPIRES", 86400)
CELERY_TASK_IGNORE_RESULT = _get_bool("CELERY_TASK_IGNORE_RESULT", default=False)
CELERY_BEAT_SCHEDULER = os.getenv("CELERY_BEAT_SCHEDULER", "celery.beat:PersistentScheduler")
CELERY_BEAT_SCHEDULE_FILENAME = os.getenv(
    "CELERY_BEAT_SCHEDULE_FILENAME",
    str(BASE_DIR / "celerybeat-schedule"),
)
CELERY_BEAT_SCHEDULE = {
    "expire-stale-orders-every-30m": {
        "task": "payments.tasks.expire_stale_orders",
        "schedule": 1800.0,  # 30 minutes
    },
    "check-membership-expiry-daily": {
        "task": "users.tasks.check_membership_expiry",
        "schedule": 86400.0,  # 24 hours
    },
    "notify-trial-expiring-daily": {
        "task": "users.tasks.notify_trial_expiring",
        "schedule": 86400.0,
    },
    "send-membership-expiry-reminders-daily": {
        "task": "users.tasks.send_membership_expiry_reminders",
        "schedule": 86400.0,
    },
    "send-expiry-reminders-daily": {
        "task": "notifications.tasks_reminder.send_expiry_reminders",
        "schedule": 86400.0,
    },
    "check-performance-drops-daily": {
        "task": "users.tasks.check_performance_drops",
        "schedule": 86400.0,
    },
    "reflect-user-learning-daily": {
        "task": "ai_assistant.tasks.reflect_user_learning",
        "schedule": 86400.0,
    },
    "reflect-teacher-patterns-daily": {
        "task": "ai_assistant.tasks.reflect_teacher_patterns",
        "schedule": 86400.0,
    },
    "cleanup-stale-memories-weekly": {
        "task": "ai_assistant.tasks.cleanup_stale_memories",
        "schedule": 604800.0,  # weekly
    },
    "aggregate-platform-stats-daily": {
        "task": "core.tasks.aggregate_daily_platform_stats",
        "schedule": 86400.0,
    },
    "analyze-trajectory-weekly": {
        "task": "ai_assistant.tasks.analyze_trajectory_task",
        "schedule": crontab(minute=0, hour=2, day_of_week=0),  # 每周日凌晨 2:00
    },
}
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": _get_int("CELERY_VISIBILITY_TIMEOUT", 3600),
}

# GIPHY
GIPHY_API_KEY = os.getenv("GIPHY_API_KEY", "")

# AI 引擎配置 → ai_engine/config.py（单一来源）

# Email — Feishu SMTP (core/email_service.py)
FEISHU_NOTIFY_PASSWORD = os.getenv("FEISHU_NOTIFY_PASSWORD", "")
EMAIL_NOREPLY_ADDRESS = os.getenv("EMAIL_NOREPLY_ADDRESS", "notification@unimind-ai.com")
UNIMIND_LOGO_URL = os.getenv("UNIMIND_LOGO_URL", "https://unimind-ai.com/logo.png")

# ── Logging（等保二级：日志持久化 + 轮转） ──
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file_api": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "api_access.log"),
            "maxBytes": 50 * 1024 * 1024,  # 50MB
            "backupCount": 180,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "file_security": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "security.log"),
            "maxBytes": 50 * 1024 * 1024,
            "backupCount": 180,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "file_agent": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "agent_debug.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "school_system.middleware": {
            "handlers": ["console", "file_api"],
            "level": "INFO",
            "propagate": False,
        },
        "core.security": {
            "handlers": ["console", "file_security"],
            "level": "INFO",
            "propagate": False,
        },
        "agent_debug": {
            "handlers": ["console", "file_agent"],
            "level": "DEBUG",
            "propagate": False,
        },
        "ai_assistant.services.tool_executor": {
            "handlers": ["console", "file_agent"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ============================================================
# 阿里云 OSS 存储配置
# ============================================================
OSS_ACCESS_KEY_ID = os.environ.get("OSS_ACCESS_KEY_ID", "")
OSS_ACCESS_KEY_SECRET = os.environ.get("OSS_ACCESS_KEY_SECRET", "")
OSS_BUCKET_NAME = os.environ.get("OSS_BUCKET_NAME", "")
OSS_ENDPOINT = os.environ.get("OSS_ENDPOINT", "")

# 如果配置了 OSS，使用 OSS 作为默认文件存储
if OSS_ACCESS_KEY_ID and OSS_ACCESS_KEY_SECRET and OSS_BUCKET_NAME and OSS_ENDPOINT:
    STORAGES = {
        "default": {
            "BACKEND": "core.oss_storage.OssMediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{OSS_BUCKET_NAME}.{OSS_ENDPOINT}/media/"


# ============================================================
# Sentry 错误追踪（仅生产环境启用）
# ============================================================
SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=DJANGO_ENV,
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
            ),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=0.2 if IS_PROD else 1.0,
        send_default_pii=False,
        attach_stacktrace=True,
        before_send=lambda event, hint: event if IS_PROD else None,
    )

