# Generated by Django 6.0.2 on 2026-05-03 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('resume', '简历深挖'), ('english', '英语口语'), ('professional', '专业课(431)'), ('mixed', '综合面试')], default='professional', max_length=20)),
                ('interviewer_style', models.CharField(choices=[('friendly', '和蔼可亲(引导为主)'), ('pressure', '压力测试(刁钻追问)')], default='friendly', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('analyzing', '复盘分析中')], default='ongoing', max_length=20)),
                ('radar_scores', models.JSONField(blank=True, default=dict, help_text='五维雷达图打分')),
                ('overall_feedback', models.TextField(blank=True, help_text='面试总体评价')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField(default=1)),
                ('speaker', models.CharField(choices=[('interviewer', '面试官'), ('candidate', '考生')], max_length=20)),
                ('content_text', models.TextField(blank=True, help_text='识别或生成的文本')),
                ('audio_url', models.URLField(blank=True, help_text='对应的音频文件URL（TTS生成或STT录音）')),
                ('latency_ms', models.IntegerField(default=0, help_text='响应延迟')),
                ('feedback_for_turn', models.TextField(blank=True, help_text='针对本轮发言的 AI 批注（仅考生发言有）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['turn_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('parsed_content', models.TextField(blank=True, help_text='OCR 解析的原始文本')),
                ('optimized_content', models.JSONField(blank=True, default=dict, help_text='AI 润色后的结构化数据')),
                ('predicted_questions', models.JSONField(blank=True, default=list, help_text='AI 针对简历预测的陷阱题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
