# Generated by Django 6.0.2 on 2026-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('ongoing', '进行中'), ('completed', '已完成'), ('analyzing', '复盘分析中')], db_index=True, default='ongoing', max_length=20),
        ),
    ]
