# Generated by Django 6.0.2 on 2026-05-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_description'),
        ('quizzes', '0022_knowledgepointannotation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_outline_enabled',
            field=models.BooleanField(default=False, verbose_name='启用AI智能大纲'),
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='大纲状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_data', models.JSONField(verbose_name='题目数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='courses.course')),
                ('question_id', models.ForeignKey(blank=True, help_text='如果已持久化到主题库则为关联 ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question', verbose_name='关联题目')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutlineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('timestamp', models.FloatField(verbose_name='时间戳（秒）')),
                ('description', models.TextField(blank=True, verbose_name='内容摘要')),
                ('index', models.PositiveIntegerField(verbose_name='显示排序')),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.courseoutline')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='zh', max_length=10, verbose_name='语言')),
                ('full_text', models.TextField(blank=True, verbose_name='完整文本')),
                ('asr_status', models.CharField(choices=[('pending', '待处理'), ('processing', '转录中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='转录状态')),
                ('asr_provider', models.CharField(blank=True, max_length=50, verbose_name='ASR 提供者')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(verbose_name='开始时间（秒）')),
                ('end_time', models.FloatField(verbose_name='结束时间（秒）')),
                ('text', models.TextField(verbose_name='文本内容')),
                ('index', models.PositiveIntegerField(verbose_name='片段序号')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='courses.videotranscript')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
