# Generated by Django 6.0.2 on 2026-05-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_ai_outline_enabled_courseoutline_and_more'),
        ('users', '0020_layer2_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.institution', verbose_name='所属机构'),
        ),
    ]
