# Generated by Django 6.0.2 on 2026-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_institution_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ai_outline_enabled',
            field=models.BooleanField(default=True, verbose_name='启用AI智能大纲'),
        ),
    ]
