# Generated by Django 6.0.2 on 2026-05-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_ai_outline_enabled_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='elo_claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ELO 奖励领取时间'),
        ),
    ]
