# Generated by Django 6.0.2 on 2026-05-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_videoprogress_elo_claimed_at'),
        ('users', '0039_institutionusagelog_ai_call_total_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('slug', models.SlugField(max_length=60, verbose_name='URL标识')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tags', to='users.institution')),
            ],
            options={
                'unique_together': {('institution', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CourseTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='courses.course')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relations', to='courses.coursetag')),
            ],
            options={
                'unique_together': {('course', 'tag')},
            },
        ),
    ]
