# Generated by Django 6.0.2 on 2026-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coursetag_coursetagrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='专辑内排序'),
        ),
    ]
