# Generated by Django 6.0.2 on 2026-05-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_sort_order'),
        ('users', '0047_plan_invite_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='users.institution', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='startupmaterial',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_materials', to='users.institution', verbose_name='所属机构'),
        ),
    ]
