# Generated by Django 6.0.2 on 2026-05-30 05:11

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_add_institution_to_album_and_startupmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseware',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.institution_upload_path, verbose_name='课件'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.institution_upload_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='reference_materials',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.institution_upload_path, verbose_name='参考资料'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.institution_upload_path),
        ),
    ]
