# Generated by Django 6.0.2 on 2026-06-18 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_courseware_alter_course_cover_image_and_more'),
        ('quizzes', '0047_add_assignment_submission_question_results'),
        ('users', '0058_backfill_institution_invites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(help_text='如 金融431、高中数学', max_length=100, verbose_name='学科')),
                ('semester', models.CharField(help_text='如 2026-春季', max_length=50, verbose_name='学期')),
                ('week_count', models.PositiveSmallIntegerField(default=18, verbose_name='教学周数')),
                ('weekly_plans', models.JSONField(blank=True, help_text='[{week:1,topic:"",objectives:"",kp_ids:[],materials:""}]', null=True, verbose_name='周计划')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plans', to='users.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teaching_plans', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_plans', to='users.institution')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('class_obj', 'subject', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='课题')),
                ('objectives', models.TextField(blank=True, verbose_name='教学目标')),
                ('activities', models.JSONField(blank=True, help_text='[{name:"导入",duration:5,description:""}]', null=True, verbose_name='教学活动')),
                ('materials', models.JSONField(blank=True, help_text='["PPT","视频","实验器材"]', null=True, verbose_name='教学材料')),
                ('ai_generated', models.JSONField(blank=True, help_text='LLM 生成的教案详细内容', null=True, verbose_name='AI 生成内容')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45, verbose_name='课时(分钟)')),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='所属周')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='users.institution')),
                ('knowledge_points', models.ManyToManyField(blank=True, related_name='lesson_plans', to='quizzes.knowledgepoint', verbose_name='知识点')),
                ('teaching_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='courses.teachingplan')),
            ],
            options={
                'ordering': ['teaching_plan', 'week_number', 'order'],
            },
        ),
    ]
