# Generated by Django 6.0.2 on 2026-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_add_teaching_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingplan',
            name='current_level',
            field=models.CharField(blank=True, help_text="如 '已掌握基础代数，薄弱在函数和解析几何'", max_length=200, verbose_name='学生当前水平'),
        ),
        migrations.AddField(
            model_name='teachingplan',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='目标截止日期'),
        ),
        migrations.AddField(
            model_name='teachingplan',
            name='goal',
            field=models.TextField(blank=True, help_text="如 '1年内达到高考数学130分'", verbose_name='教学目标'),
        ),
        migrations.AddField(
            model_name='teachingplan',
            name='milestones',
            field=models.JSONField(blank=True, help_text='[{week:4, target:"函数章节掌握80%", achieved:false}]', null=True, verbose_name='里程碑'),
        ),
        migrations.AddField(
            model_name='teachingplan',
            name='target_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='目标分数'),
        ),
    ]
