# Generated by Django 6.0.2 on 2026-06-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_add_teaching_plan_goals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonPlan',
        ),
    ]
