# Generated by Django 6.0.2 on 2026-08-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0025_delete_studyplan'),
        ('courses', '0021_remove_lesson_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingPlan',
        ),
    ]
