# Generated by Django 6.0.2 on 2026-05-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0004_studyplan_weeklytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='weekly_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI周报摘要'),
        ),
    ]
