# Generated by Django 6.0.2 on 2026-05-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0006_chatmessage_message_type'),
        ('users', '0026_membership_tier_4level'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='users.institution', verbose_name='所属机构'),
        ),
    ]
