# Generated by Django 6.0.2 on 2026-05-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0007_chatmessage_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklytask',
            name='knowledge_point',
        ),
        migrations.RemoveField(
            model_name='weeklytask',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudyPlan',
        ),
        migrations.DeleteModel(
            name='WeeklyTask',
        ),
    ]
