# Generated by Django 6.0.2 on 2026-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0008_remove_weeklytask_knowledge_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('chat', '聊天消息'), ('task_start', '任务开始'), ('task_stop', '任务中止'), ('task_complete', '任务完成'), ('plan_complete', '计划完成'), ('plan_create', '制定计划')], db_index=True, default='chat', max_length=20, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
