# Generated by Django 6.0.2 on 2026-06-26 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0009_alter_chatmessage_message_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('ended', '已结束')], db_index=True, default='active', max_length=10)),
                ('task_name', models.CharField(blank=True, default='', max_length=200)),
                ('duration_minutes', models.IntegerField(default=25)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_focus_seconds', models.IntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
