# Generated by Django 6.0.2 on 2026-08-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_room', '0010_add_study_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyTask',
        ),
    ]
