# Generated by Django 6.0.2 on 2026-05-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=20),
        ),
    ]
