# Generated by Django 6.0.2 on 2026-06-20 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_subscription_model'),
        ('users', '0059_add_institution_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='使用的优惠码'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_cents',
            field=models.IntegerField(default=0, verbose_name='优惠金额(分)'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='优惠码')),
                ('discount_type', models.CharField(choices=[('percent', '百分比折扣'), ('fixed', '固定金额减免')], max_length=10, verbose_name='折扣类型')),
                ('discount_value', models.IntegerField(help_text='percent: 1-100; fixed: 分', verbose_name='折扣值')),
                ('min_order_cents', models.IntegerField(default=0, verbose_name='最低订单金额(分)')),
                ('max_uses', models.IntegerField(default=0, help_text='0=无限制', verbose_name='总使用次数上限')),
                ('current_uses', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('max_uses_per_user', models.IntegerField(default=1, verbose_name='每人限用次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('plan_restriction', models.CharField(blank=True, help_text='逗号分隔，空=全部方案', max_length=100, verbose_name='适用方案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, help_text='NULL=平台通用', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='推荐码')),
                ('clicks', models.IntegerField(default=0, verbose_name='点击次数')),
                ('signups', models.IntegerField(default=0, verbose_name='注册数')),
                ('purchases', models.IntegerField(default=0, verbose_name='购买数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推荐码',
                'verbose_name_plural': '推荐码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_granted', models.BooleanField(default=False)),
                ('reward_amount_cents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_records', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '推荐记录',
                'verbose_name_plural': '推荐记录',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referee')},
            },
        ),
        migrations.CreateModel(
            name='UserCouponUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_uses', to='payments.coupon')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_applied', to='payments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '优惠券使用记录',
                'verbose_name_plural': '优惠券使用记录',
                'unique_together': {('user', 'coupon', 'order')},
            },
        ),
    ]
