# Generated by Django 6.0.2 on 2026-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_coupons_referrals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_customer_id',
            new_name='gateway_customer_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='gateway_subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(default='stub', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway',
            field=models.CharField(choices=[('stub', 'Stub (开发)'), ('wechat', 'WeChat Pay'), ('alipay', 'Alipay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
