# Generated by Django 6.0.2 on 2026-04-30 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_systemconfig_unimind_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='权限组键')),
                ('name', models.CharField(max_length=80, verbose_name='权限组名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='权限组说明')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限点列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                ('color', models.CharField(default='slate', max_length=20, verbose_name='颜色标识')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='标签说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_permissions', models.JSONField(blank=True, default=list, verbose_name='附加权限点')),
                ('blocked_permissions', models.JSONField(blank=True, default=list, verbose_name='屏蔽权限点')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='管理备注')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_groups', models.ManyToManyField(blank=True, related_name='users', to='users.permissiongroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='users', to='users.usertag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
