# Generated by Django 6.0.2 on 2026-05-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_permissiongroup_usertag_useraccessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('cross_major', '跨考'), ('same_major', '本专业')], default='same_major', max_length=20, verbose_name='考生类型')),
                ('target_university', models.CharField(blank=True, max_length=100, verbose_name='目标院校')),
                ('tags', models.ManyToManyField(blank=True, related_name='user_profiles', to='users.usertag', verbose_name='用户标签')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
