# Generated by Django 6.0.2 on 2026-05-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_tier',
            field=models.CharField(choices=[('free', '免费'), ('basic', '基础'), ('pro', '专业')], default='free', max_length=20, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='试用到期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='验证码'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证码发送时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
