# Generated by Django 6.0.2 on 2026-05-10 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_email_verified_user_membership_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_role',
            field=models.CharField(choices=[('admin', '机构管理员'), ('student', '学员')], default='student', max_length=20, verbose_name='机构内角色'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='机构名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='机构标识')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('solo', 'Solo'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='当前版本')),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='版本到期时间')),
                ('max_students_override', models.IntegerField(blank=True, null=True, verbose_name='学员上限覆写')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('custom_domain', models.CharField(blank=True, max_length=200, verbose_name='自定义域名')),
                ('logo', models.ImageField(blank=True, upload_to='institution_logos/', verbose_name='机构 Logo')),
                ('notes', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_institutions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.institution', verbose_name='所属机构'),
        ),
    ]
