# Generated by Django 6.0.2 on 2026-05-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_institution_role_institution_user_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.institution')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '机构操作日志',
                'verbose_name_plural': '机构操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='计费周期起始')),
                ('ai_generation_count', models.IntegerField(default=0, verbose_name='AI 出题次数')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.institution')),
            ],
            options={
                'verbose_name': '机构用量日志',
                'verbose_name_plural': '机构用量日志',
                'ordering': ['-period_start'],
                'unique_together': {('institution', 'period_start')},
            },
        ),
    ]
