# Generated by Django 6.0.2 on 2026-05-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_commercial_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_merchant_id', models.CharField(blank=True, max_length=32, verbose_name='微信商户号')),
                ('wechat_api_v3_key', models.CharField(blank=True, max_length=64, verbose_name='微信 APIv3 Key')),
                ('wechat_cert_serial', models.CharField(blank=True, max_length=40, verbose_name='证书序列号')),
                ('alipay_app_id', models.CharField(blank=True, max_length=32, verbose_name='支付宝 App ID')),
                ('alipay_private_key', models.TextField(blank=True, verbose_name='支付宝私钥')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='启用学生端收费')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构收款配置',
                'verbose_name_plural': '机构收款配置',
            },
        ),
        migrations.CreateModel(
            name='InstitutionProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('course', '课程'), ('membership', '会员'), ('exam', '模考')], max_length=20, verbose_name='产品类型')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='产品 ID')),
                ('price', models.IntegerField(verbose_name='价格（分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构产品定价',
                'verbose_name_plural': '机构产品定价',
                'unique_together': {('institution', 'product_type', 'product_id')},
            },
        ),
    ]
