# Generated by Django 6.0.2 on 2026-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_layer2_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='邀请码'),
        ),
    ]
