# Generated by Django 6.0.2 on 2026-05-12 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_institution_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='邀请码')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('solo', 'Solo'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20, verbose_name='对应方案')),
                ('max_uses', models.IntegerField(default=1, verbose_name='可使用次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '方案邀请码',
                'verbose_name_plural': '方案邀请码',
                'ordering': ['-created_at'],
            },
        ),
    ]
