# Generated by Django 6.0.2 on 2026-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_planinvitecode_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='有效天数（0=永久）'),
        ),
    ]
