# Generated by Django 6.0.2 on 2026-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_activationcode_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='invite_slug',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='邀请链接 slug'),
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='有效天数'),
        ),
    ]
