# Generated by Django 6.0.2 on 2026-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_add_institution_invite_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_tier',
            field=models.CharField(choices=[('free', 'Free'), ('solo', 'Solo'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='会员等级'),
        ),
    ]
