# Generated by Django 6.0.2 on 2026-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_membership_tier_4level'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, verbose_name='机构简介'),
        ),
    ]
