# Generated by Django 6.0.2 on 2026-05-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_institution_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionProductPrice',
        ),
    ]
