# Generated by Django 6.0.2 on 2026-05-16 02:07

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_delete_institutionproductprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionpaymentconfig',
            name='alipay_private_key',
            field=core.fields.EncryptedTextField(blank=True, verbose_name='支付宝私钥'),
        ),
        migrations.AlterField(
            model_name='institutionpaymentconfig',
            name='wechat_api_v3_key',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='微信 APIv3 Key'),
        ),
    ]
