# Generated by Django 6.0.2 on 2026-05-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_institutionpaymentconfig_alipay_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='验证码哈希'),
        ),
    ]
