# Generated by Django 6.0.2 on 2026-05-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_delete_institutionproductprice'),
        ('users', '0030_alter_user_verification_code'),
    ]

    operations = [
    ]
