# Generated by Django 6.0.2 on 2026-05-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='invite_code',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='invite_code',
        ),
    ]
