# Generated by Django 6.0.2 on 2026-05-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_institution_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution_role',
            field=models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('student', '学员')], default='student', max_length=20, verbose_name='机构内角色'),
        ),
    ]
