# Generated by Django 6.0.2 on 2026-05-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_nickname'),
        ('users', '0027_add_institution_invite_slug'),
        ('users', '0031_merge_20260516_1503'),
    ]

    operations = [
    ]
