# Generated by Django 6.0.2 on 2026-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_20260516_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='invite_code',
            field=models.CharField(default='UNIMIND2026', max_length=50, verbose_name='邀请码'),
        ),
    ]
