# Generated by Django 6.0.2 on 2026-05-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_institution_role_owner_teacher'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE users_user SET institution_role = 'owner' WHERE institution_role = 'admin';",
            reverse_sql="UPDATE users_user SET institution_role = 'admin' WHERE institution_role = 'owner';",
        ),
    ]
