# Generated by Django 6.0.2 on 2026-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_migrate_admin_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='business_type',
            field=models.CharField(blank=True, help_text='您主要讲授的课程，如考研英语、高等数学、GRE、IELTS。此项与模拟面试、AI助教等多个功能关联，请务必正确填写。', max_length=200, verbose_name='主营业务'),
        ),
    ]
