# Generated by Django 6.0.2 on 2026-05-17 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_institution_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elo_points',
            field=models.IntegerField(default=0, verbose_name='可消费积分'),
        ),
        migrations.CreateModel(
            name='EloPointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动数量（正=获得，负=消费）')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('reason', models.CharField(choices=[('exam_complete', '测验完成'), ('question_graded', '题目判分'), ('course_complete', '课程完成'), ('course_reward_claim', '课程奖励领取'), ('shop_redeem', '积分兑换'), ('admin_adjust', '管理员调整'), ('elo_reset', 'ELO重置')], max_length=30, verbose_name='变动原因')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='关联类型')),
                ('reference_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
            },
        ),
    ]
