# Generated by Django 6.0.2 on 2026-05-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_elo_points_elopointsledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用积分功能')),
                ('points_multiplier', models.FloatField(default=1.0, verbose_name='积分倍率')),
                ('monthly_bonus_points', models.IntegerField(default=0, verbose_name='每月赠送积分')),
                ('daily_login_bonus', models.IntegerField(default=5, verbose_name='每日登录积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_config', to='users.institution')),
            ],
            options={
                'verbose_name': '机构积分配置',
                'verbose_name_plural': '机构积分配置',
            },
        ),
    ]
