# Generated by Django 6.0.2 on 2026-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_institutionrewardconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='elo_points',
            field=models.IntegerField(default=50, verbose_name='可消费积分'),
        ),
    ]
