# Generated by Django 6.0.2 on 2026-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_user_elo_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='business_type',
            field=models.CharField(blank=True, help_text='您主要讲授的课程，如金融431、CPA、法考、教资等。此项与模拟面试、AI助教等多个功能关联，请务必正确填写。', max_length=200, verbose_name='主营业务'),
        ),
    ]
