# Generated by Django 6.0.2 on 2026-05-21 14:32

from django.db import migrations, models


def backfill_ai_question_count(apps, schema_editor):
    InstitutionUsageLog = apps.get_model('users', 'InstitutionUsageLog')
    InstitutionUsageLog.objects.filter(ai_question_count=0).update(
        ai_question_count=models.F('ai_generation_count'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_institution_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionusagelog',
            name='ai_call_total_count',
            field=models.IntegerField(default=0, verbose_name='AI 调用总次数(不含ASR)'),
        ),
        migrations.AddField(
            model_name='institutionusagelog',
            name='ai_question_count',
            field=models.IntegerField(default=0, verbose_name='AI 出题次数'),
        ),
        migrations.AddField(
            model_name='institutionusagelog',
            name='interview_count',
            field=models.IntegerField(default=0, verbose_name='面试场次'),
        ),
        migrations.AddField(
            model_name='institutionusagelog',
            name='pdf_export_count',
            field=models.IntegerField(default=0, verbose_name='模拟考试PDF次数'),
        ),
        migrations.AlterField(
            model_name='institutionusagelog',
            name='ai_generation_count',
            field=models.IntegerField(default=0, verbose_name='AI 出题次数(旧)'),
        ),
        migrations.RunPython(backfill_ai_question_count, migrations.RunPython.noop),
    ]
