# Generated by Django 6.0.2 on 2026-05-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_institutionusagelog_ai_call_total_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionrewardconfig',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='elo_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='elo_reset_count',
        ),
        migrations.DeleteModel(
            name='EloPointsLedger',
        ),
        migrations.DeleteModel(
            name='InstitutionRewardConfig',
        ),
    ]
