# Generated by Django 6.0.2 on 2026-05-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_institutionrewardconfig_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.IntegerField(default=0, verbose_name='连续登录失败次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间'),
        ),
    ]
