# Generated by Django 6.0.2 on 2026-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_security_lockout_and_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='当前版本'),
        ),
        migrations.AlterField(
            model_name='planinvitecode',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='对应方案'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='会员等级'),
        ),
    ]
