# Generated by Django 6.0.2 on 2026-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_examtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='小宇 Dashboard 配置'),
        ),
    ]
