# Generated by Django 6.0.2 on 2026-05-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_user_dashboard_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='student_scale',
            field=models.CharField(blank=True, choices=[('1-50', '1-50 人'), ('50-200', '50-200 人'), ('200-500', '200-500 人'), ('500+', '500+ 人')], default='', max_length=20, verbose_name='学员规模'),
        ),
    ]
