# Generated by Django 6.0.2 on 2026-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_add_student_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, verbose_name='已用存储(字节)'),
        ),
    ]
