# Generated by Django 6.0.2 on 2026-05-29 11:28

from django.db import migrations, models


def migrate_trial_to_membership(apps, schema_editor):
    """Existing trial users: copy trial_ends_at → membership_expires_at, set source='trial'."""
    User = apps.get_model('users', 'User')
    # Trial users: is_member=True, tier='free', has trial_ends_at, no membership_expires_at
    trial_users = User.objects.filter(
        is_member=True, membership_tier='free',
        trial_ends_at__isnull=False, membership_expires_at__isnull=True,
    )
    for u in trial_users:
        u.membership_expires_at = u.trial_ends_at
        u.membership_source = 'trial'
        u.save(update_fields=['membership_expires_at', 'membership_source'])

    # Paid users: is_member=True, has membership_expires_at
    paid_users = User.objects.filter(
        is_member=True, membership_expires_at__isnull=False,
        membership_source__isnull=True,
    )
    paid_users.update(membership_source='code')

    # Existing unused activation codes: set code_type='formal', membership_tier='growth'
    ActivationCode = apps.get_model('users', 'ActivationCode')
    ActivationCode.objects.filter(code_type='formal').update(membership_tier='growth')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_institution_storage_used_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='code_type',
            field=models.CharField(choices=[('trial', '试用'), ('formal', '正式')], default='formal', max_length=10, verbose_name='码类型'),
        ),
        migrations.AddField(
            model_name='activationcode',
            name='membership_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='growth', max_length=20, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_source',
            field=models.CharField(blank=True, choices=[('trial', '试用'), ('code', '激活码'), ('payment', '付费'), ('admin', '管理员')], max_length=20, null=True, verbose_name='会员来源'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='试用到期时间（已废弃，保留兼容）'),
        ),
        migrations.RunPython(migrate_trial_to_membership, reverse_noop),
    ]
