# Generated by Django 6.0.2 on 2026-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_activation_code_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinvitecode',
            name='code_type',
            field=models.CharField(choices=[('trial', '试用'), ('formal', '正式')], default='formal', max_length=10, verbose_name='码类型'),
        ),
    ]
