# Generated by Django 6.0.2 on 2026-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_plan_invite_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='已同意用户协议'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='同意协议时间'),
        ),
    ]
