# Generated by Django 6.0.2 on 2026-06-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_user_agreed_to_terms_user_agreed_to_terms_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用到期提醒')),
                ('channel', models.CharField(choices=[('email', '邮件'), ('feishu', '飞书')], default='email', max_length=20, verbose_name='通知渠道')),
                ('due_threshold', models.IntegerField(default=5, help_text='学生到期题目超过此数量时发送通知', verbose_name='触发阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构通知配置',
                'verbose_name_plural': '机构通知配置',
            },
        ),
    ]
