# Generated by Django 6.0.2 on 2026-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='has_used_bulk_init',
            field=models.BooleanField(default=False, verbose_name='已使用批量初始化出题'),
        ),
    ]
