# Generated by Django 6.0.2 on 2026-06-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_courseware_alter_course_cover_image_and_more'),
        ('users', '0052_add_has_used_bulk_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='users.class', verbose_name='班级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='courses.course', verbose_name='课程')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_courses', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '班级课程',
                'verbose_name_plural': '班级课程',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('class_obj', 'course'), name='unique_class_course')],
            },
        ),
    ]
