# Generated by Django 6.0.2 on 2026-06-17 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_classcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='成就标识')),
                ('name', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.CharField(max_length=200, verbose_name='成就描述')),
                ('icon', models.CharField(default='🏆', max_length=20, verbose_name='图标')),
                ('category', models.CharField(choices=[('streak', '连续打卡'), ('diagnostic', '首次诊断'), ('question', '刷题里程碑'), ('mastery', '掌握知识点'), ('exam', '考试成绩'), ('social', '社交互动')], default='streak', max_length=20, verbose_name='分类')),
                ('threshold', models.PositiveIntegerField(default=1, verbose_name='触发阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '成就定义',
                'verbose_name_plural': '成就定义',
                'ordering': ['category', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='签到日期')),
                ('streak', models.PositiveIntegerField(default=1, verbose_name='连续天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日签到',
                'verbose_name_plural': '每日签到',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_check_in')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='当前进度')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
