# Generated by Django 6.0.2 on 2026-06-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_add_achievements_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='接收邮件通知'),
        ),
    ]
