# Generated by Django 6.0.2 on 2026-06-17 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(verbose_name='Push Endpoint')),
                ('p256dh', models.TextField(verbose_name='p256dh Key')),
                ('auth', models.TextField(verbose_name='Auth Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '推送订阅',
                'verbose_name_plural': '推送订阅',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
