# Generated by Django 6.0.2 on 2026-06-18 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_push_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution_role',
            field=models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('registrar', '教务主管'), ('student', '学员')], default='student', max_length=20, verbose_name='机构内角色'),
        ),
        migrations.CreateModel(
            name='InstitutionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40, unique=True, verbose_name='邀请标识')),
                ('assigned_role', models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('registrar', '教务主管'), ('student', '学员')], default='student', max_length=20, verbose_name='分配角色')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大使用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='需要审批')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构邀请链接',
                'verbose_name_plural': '机构邀请链接',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='申请留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.institution', verbose_name='目标机构')),
                ('invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='users.institutioninvite', verbose_name='通过邀请链接')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_request', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '加入申请',
                'verbose_name_plural': '加入申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
