# Generated by Django 6.0.2 on 2026-06-18 15:55

from django.db import migrations


def backfill_invite_slugs(apps, schema_editor):
    """为每个有 invite_slug 的 Institution 创建一条 InstitutionInvite。"""
    Institution = apps.get_model('users', 'Institution')
    InstitutionInvite = apps.get_model('users', 'InstitutionInvite')
    for inst in Institution.objects.exclude(invite_slug='').exclude(invite_slug__isnull=True):
        if not InstitutionInvite.objects.filter(slug=inst.invite_slug).exists():
            InstitutionInvite.objects.create(
                institution=inst,
                slug=inst.invite_slug,
                assigned_role='student',
                requires_approval=False,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_institution_invite_and_join_request'),
    ]

    operations = [
        migrations.RunPython(backfill_invite_slugs, reverse_code=migrations.RunPython.noop),
    ]
