# Generated by Django 6.0.2 on 2026-06-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_backfill_institution_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='inherit_plan',
            field=models.BooleanField(default=True, help_text='为真时 plan/plan_expires_at 从 parent 实时派生', verbose_name='继承上级方案'),
        ),
        migrations.AddField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.institution', verbose_name='上级机构'),
        ),
    ]
