# Generated by Django 6.0.2 on 2026-06-20 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_add_institution_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioninvite',
            name='assigned_role',
            field=models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('registrar', '教务主管'), ('student', '学员'), ('parent', '家长')], default='student', max_length=20, verbose_name='分配角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution_role',
            field=models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('registrar', '教务主管'), ('student', '学员'), ('parent', '家长')], default='student', max_length=20, verbose_name='机构内角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('admin', '管理员'), ('parent', '家长')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False, verbose_name='已验证')),
                ('verification_code', models.CharField(blank=True, max_length=10, verbose_name='绑定验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家长关联',
                'verbose_name_plural': '家长关联',
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
