# Generated by Django 6.0.2 on 2026-06-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_institutioninvite_assigned_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='凭证名称')),
                ('key_id', models.CharField(help_text='ak- 前缀，公开标识', max_length=40, unique=True, verbose_name='API Key ID')),
                ('key_secret_hash', models.CharField(max_length=128, verbose_name='API Secret 哈希')),
                ('scopes', models.JSONField(default=list, help_text='["read:questions","read:analytics"]', verbose_name='权限范围')),
                ('rate_limit', models.IntegerField(default=60, verbose_name='速率限制(次/分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_credentials', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='users.institution')),
            ],
            options={
                'verbose_name': 'API 凭证',
                'verbose_name_plural': 'API 凭证',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('feishu', '飞书 (Feishu)'), ('dingtalk', '钉钉 (DingTalk)'), ('wecom', '企业微信 (WeCom)'), ('generic_oidc', '通用 OIDC')], max_length=20, verbose_name='SSO 提供商')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID / App ID')),
                ('client_secret', models.CharField(max_length=500, verbose_name='Client Secret')),
                ('redirect_uri', models.CharField(blank=True, max_length=300, verbose_name='回调地址')),
                ('domain_whitelist', models.JSONField(blank=True, default=list, help_text='用户邮箱/域名匹配后才自动加入机构', verbose_name='域名白名单')),
                ('auto_join', models.BooleanField(default=True, verbose_name='首次 SSO 登录自动加入机构')),
                ('default_role', models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='student', max_length=20, verbose_name='默认机构角色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='users.institution', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': 'SSO 配置',
                'verbose_name_plural': 'SSO 配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
