# Generated by Django 6.0.2 on 2026-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_add_api_sso_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.CharField(blank=True, help_text='如：物理、数学、公考', max_length=100, verbose_name='班级分类'),
        ),
    ]
