# Generated by Django 6.0.2 on 2026-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_cleanup_roles_remove_registrar_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='个人方案（无机构用户）'),
        ),
        migrations.AlterField(
            model_name='institutioninvite',
            name='assigned_role',
            field=models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('student', '学员')], default='student', max_length=20, verbose_name='分配角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution_role',
            field=models.CharField(choices=[('owner', '机构所有者'), ('teacher', '教师'), ('student', '学员')], default='student', max_length=20, verbose_name='机构内角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='会员等级（已弃用，迁移至 personal_plan）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('admin', '管理员')], default='student', max_length=10),
        ),
    ]
