# Generated by Django 6.0.2 on 2026-06-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_populate_personal_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='引导已关闭时间'),
        ),
    ]
