# Generated by Django 6.0.2 on 2026-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_user_tour_dismissed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_panel_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='面板引导已关闭时间'),
        ),
    ]
