# Generated by Django 6.0.2 on 2026-08-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_delete_teachingplan'),
        ('quizzes', '0053_remove_assignmentquestion_assignment_and_more'),
        ('users', '0067_user_tour_panel_dismissed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionPaymentConfig',
        ),
        migrations.DeleteModel(
            name='ClassCourse',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
