# Generated by Django 6.0.2 on 2026-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: AI_QUESTION_REVIEWER', max_length=100, unique=True)),
                ('version', models.CharField(help_text='例如: v1.2.0', max_length=20)),
                ('content', models.TextField(help_text='Prompt 的系统指令内容, 支持 Jinja2/F-string 变量占位符')),
                ('agent_role', models.CharField(choices=[('GENERATOR', '出题者'), ('REVIEWER', '审核者'), ('TAGGER', '打标者')], default='GENERATOR', max_length=50)),
                ('model_provider', models.CharField(default='gpt-4o', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
