# Generated by Django 6.0.2 on 2026-05-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('quizzes', '0022_knowledgepointannotation_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('chat', 'AI 助教对话'), ('generate_author', '出题 — Author'), ('generate_reviewer', '出题 — Reviewer'), ('generate_classifier', '出题 — Classifier'), ('grade_subjective', '主观题评分'), ('parse_text', '文本解析'), ('generate_answer', '生成题目解析'), ('essay_grade', '作文精细评分'), ('interview', '模拟面试'), ('schema_repair', 'JSON 结构修复'), ('fallback', '通用回退')], max_length=30, unique=True, verbose_name='任务类型')),
                ('model_name', models.CharField(help_text='如 deepseek-ai/DeepSeek-V3.2', max_length=100, verbose_name='模型名称')),
                ('provider', models.CharField(default='siliconflow', max_length=30, verbose_name='提供商')),
                ('temperature', models.FloatField(default=0.4, verbose_name='温度')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大 Token 数')),
                ('priority', models.IntegerField(default=0, help_text='数字越小优先级越高，作为备用模型的选择顺序', verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'ordering': ['task_type'],
            },
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='agent_role',
            field=models.CharField(choices=[('AUTHOR', '出题者'), ('REVIEWER', '审核者'), ('CLASSIFIER', '分类器'), ('GRADER', '评分者'), ('ASSISTANT', '助教'), ('PARSER', '解析器')], default='AUTHOR', max_length=50),
        ),
        migrations.CreateModel(
            name='PromptQualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('chat', 'AI 助教对话'), ('generate_author', '出题 — Author'), ('generate_reviewer', '出题 — Reviewer'), ('generate_classifier', '出题 — Classifier'), ('grade_subjective', '主观题评分'), ('parse_text', '文本解析'), ('generate_answer', '生成题目解析'), ('essay_grade', '作文精细评分'), ('interview', '模拟面试'), ('schema_repair', 'JSON 结构修复'), ('fallback', '通用回退')], max_length=30, verbose_name='任务类型')),
                ('prompt_version', models.CharField(max_length=20, verbose_name='使用的 Prompt 版本')),
                ('accepted', models.BooleanField(default=False, verbose_name='结果是否被接受')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量分 (0-1)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='额外元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_logs', to='quizzes.contentpipelinetask')),
                ('prompt_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_logs', to='core.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prompt_template', '-created_at'], name='core_prompt_prompt__c8774f_idx'), models.Index(fields=['task_type', 'accepted'], name='core_prompt_task_ty_7d78e0_idx')],
            },
        ),
    ]
