# Generated by Django 6.0.2 on 2026-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aimodelconfig_alter_prompttemplate_agent_role_and_more'),
        ('quizzes', '0022_knowledgepointannotation_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIModelConfig',
        ),
        migrations.RemoveIndex(
            model_name='promptqualitylog',
            name='core_prompt_prompt__c8774f_idx',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='model_provider',
        ),
        migrations.AddField(
            model_name='promptqualitylog',
            name='prompt_name',
            field=models.CharField(default='', max_length=100, verbose_name='Prompt 名称'),
        ),
        migrations.AddIndex(
            model_name='promptqualitylog',
            index=models.Index(fields=['prompt_name', '-created_at'], name='core_prompt_prompt__40b46f_idx'),
        ),
        migrations.RemoveField(
            model_name='promptqualitylog',
            name='prompt_template',
        ),
    ]
