# Generated by Django 6.0.2 on 2026-05-25 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aimodelconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', '登录成功'), ('login_failure', '登录失败'), ('login_locked', '账号锁定'), ('password_change', '密码变更'), ('permission_change', '权限变更'), ('admin_action', '管理操作')], max_length=30, verbose_name='事件类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='Request ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '安全审计日志',
                'verbose_name_plural': '安全审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='core_securi_event_t_34c0be_idx'), models.Index(fields=['user', '-created_at'], name='core_securi_user_id_d02b9b_idx')],
            },
        ),
    ]
