# Generated by Django 6.0.2 on 2026-05-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_security_lockout_and_audit'),
        ('users', '0047_plan_invite_code_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_users', models.IntegerField(default=0, verbose_name='总用户数')),
                ('new_users', models.IntegerField(default=0, verbose_name='新增用户')),
                ('dau', models.IntegerField(default=0, verbose_name='DAU')),
                ('wau', models.IntegerField(default=0, verbose_name='WAU')),
                ('mau', models.IntegerField(default=0, verbose_name='MAU')),
                ('total_institutions', models.IntegerField(default=0, verbose_name='总机构数')),
                ('new_institutions', models.IntegerField(default=0, verbose_name='新增机构')),
                ('active_institutions', models.IntegerField(default=0, verbose_name='活跃机构')),
                ('quiz_attempts', models.IntegerField(default=0, verbose_name='答题次数')),
                ('quiz_correct_rate', models.FloatField(default=0, verbose_name='答题正确率')),
                ('diagnostic_completions', models.IntegerField(default=0, verbose_name='诊断完成数')),
                ('ai_chat_sessions', models.IntegerField(default=0, verbose_name='AI对话次数')),
                ('ai_calls_total', models.IntegerField(default=0, verbose_name='AI调用总量')),
                ('course_views', models.IntegerField(default=0, verbose_name='课程浏览')),
                ('course_completions', models.IntegerField(default=0, verbose_name='课程完成')),
                ('pdf_exports', models.IntegerField(default=0, verbose_name='PDF导出')),
                ('day1_retention', models.FloatField(default=0, verbose_name='次日留存率')),
                ('day7_retention', models.FloatField(default=0, verbose_name='7日留存率')),
                ('day30_retention', models.FloatField(default=0, verbose_name='30日留存率')),
            ],
            options={
                'verbose_name': '每日平台统计',
                'verbose_name_plural': '每日平台统计',
                'db_table': 'core_daily_platform_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='评分 (0-10)')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='文字反馈')),
                ('source', models.CharField(choices=[('auto', '系统弹出'), ('manual', '主动提交')], default='auto', max_length=50, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_surveys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'NPS问卷',
                'verbose_name_plural': 'NPS问卷',
                'db_table': 'core_nps_survey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_login', '用户登录'), ('diagnostic_start', '诊断开始'), ('diagnostic_complete', '诊断完成'), ('quiz_attempt', '刷题'), ('ai_chat_start', 'AI对话开始'), ('course_view', '课程浏览'), ('course_complete', '课程完成'), ('pdf_export', 'PDF导出'), ('invite_click', '邀请链接点击')], db_index=True, max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='属性')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='users.institution', verbose_name='机构')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分析事件',
                'verbose_name_plural': '分析事件',
                'db_table': 'core_analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='core_analyt_event_t_e5dcf5_idx'), models.Index(fields=['institution', 'created_at'], name='core_analyt_institu_4bd370_idx')],
            },
        ),
    ]
