# Generated by Django 6.0.2 on 2026-06-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailyplatformstats_npssurvey_analyticsevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug 反馈'), ('feature', '功能建议'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='联系方式')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='页面 URL')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'db_table': 'core_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('privacy', '隐私政策'), ('terms', '用户协议')], max_length=20, verbose_name='文档类型')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文 (HTML/Markdown)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '法律文档',
                'verbose_name_plural': '法律文档',
                'db_table': 'core_legal_document',
                'ordering': ['-effective_date'],
                'unique_together': {('doc_type', 'version')},
            },
        ),
    ]
